### Получить всех сотрудников
GET http://localhost:8080/employees

### Создать сотрудника 1
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Test",
  "department": 1,
  "salary": 1000
}

### Создать сотрудника 2
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Test2",
  "lastName": "Test2",
  "department": 2,
  "salary": 3000
}
### Создать сотрудника 3
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Test3",
  "lastName": "Test3",
  "department": 1,
  "salary": 5000
}
### Получить сумму зарплат по сотрудникам
GET http://localhost:8080/employees/salary/sum
### Получение сотрудника с минимальной зарплатой
GET http://localhost:8080/employees/salary/min
### Получение сотрудника с максимальной зарплатой
GET http://localhost:8080/employees/salary/max
### Получение всех сотрудников, зарплата которых больше средней зарплаты
GET http://localhost:8080/employees/salary/high-salary
### Получить сотрудников по департаменту 1
GET http://localhost:8080/department/1/employees
### Получить сумму зарплат по департаменту 1
GET http://localhost:8080/department/1/salary/sum
### Получить сумму зарплат по департаменту 2
GET http://localhost:8080/department/2/salary/sum
### Получить максимальную зарплату по департаменту 1
GET http://localhost:8080/department/1/salary/max
### Получить минимальную зарплату по департаменту 1
GET http://localhost:8080/department/1/salary/min
### Получить сотрудников, сгруппированых по отделам
GET http://localhost:8080/department/employees